config/routes.rb
EwhaNote::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'user_sessions' }

  resources :lectures do
    get :search, on: :collection
    resources :assessments
  end

  resources :assessments
  resources :registrations, only: [:new, :create]

  root :to => 'assessments#index'
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  include Tire::Model::Search

  has_many :assessments
  has_many :taggings
  after_initialize :initialize_with_defaults

  validates :provider, uniqueness: { scope: :title }

  index_prefix 'dongguk'
  mapping do
    indexes :id, :type => 'string', :index => :not_analyzed
    indexes :title
    indexes :provider
  end

  def initialize_with_defaults
    self.upvote_count ||= 0
    self.downvote_count ||= 0
    self.assessment_count ||= 0
    self.hit_count ||= 0

    self.overall_score ||= 0
    self.presentation_score ||= 0
    self.workload_score ||= 0
    self.grading_score ||= 0
    self.difficulty_score ||= 0
    self.insight_score ||= 0
  end

  def update_assessment_count
    sql = <<-SQL
      SELECT
        COUNT(*) as count,
        AVG(overall_score) as overall_score,
        AVG(presentation_score) as presentation_score,
        AVG(workload_score) as workload_score,
        AVG(grading_score) as grading_score,
        AVG(difficulty_score) as difficulty_score,
        AVG(insight_score) as insight_score
      FROM assessments
      WHERE lecture_id = #{id}
    SQL

    aggregated = ActiveRecord::Base.connection.execute(sql).first

    if aggregated.is_a? Hash
      self.assessment_count = aggregated['count']
      self.overall_score = aggregated['overall_score']
      self.presentation_score = aggregated['presentation_score']
      self.workload_score = aggregated['workload_score']
      self.grading_score = aggregated['grading_score']
      self.difficulty_score = aggregated['difficulty_score']
      self.insight_score = aggregated['insight_score']
    else
      self.assessment_count = aggregated[0]
      self.overall_score = aggregated[1]
      self.presentation_score = aggregated[2]
      self.workload_score = aggregated[3]
      self.grading_score = aggregated[4]
      self.difficulty_score = aggregated[5]
      self.insight_score = aggregated[6]
    end

    save
  end

  def update_hit_count
    self.hit_count += 1
    save
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
    @lectures = Lecture.paginate(page: params[:page] || 1)
  end

  def search
    @query = params[:query]
    @query.gsub!(/[+\-|!(){}\[\]\^"~*?:\\]/, "\\\\\\0") if @query

    if @query && @query.length > 0
      @lectures = Lecture.search("*#{@query}*", :page => params[:page] || 1, :per_page => 10, :load => true)
    else
      @lectures = Lecture.paginate :page => params[:page] || 1
    end

    render :index
  end

  def show
    @lecture = Lecture.find params[:id]
    @lecture.update_hit_count
    @assessment = Assessment.new
    @assessments = @lecture.assessments.all
  end
end

app/helpers/lectures_helper.rb
# encoding=utf-8

module LecturesHelper
  def lecture_container(lecture, rank = nil)
    elements = []

    elements << (content_tag :span, '{', class: 'curly-braces')
    elements << (content_tag :span, lecture.provider, class: 'provider')
    elements << (content_tag :span, '/', class: 'separator')
    elements << (content_tag :span, lecture.title, class: 'title')
    elements << (content_tag :span, '}', class: 'curly-braces')


    if rank
      rank_element = content_tag('div', content_tag('span', rank, class: 'number').html_safe + content_tag('span', '.', class: 'tail').html_safe, class: 'rank').html_safe
      main_div = content_tag('div', elements.join('').html_safe, class: 'lecture').html_safe

      content_tag('div', rank_element + main_div, class: 'ranked-lecture').html_safe
    else
      content_tag('div', elements.join('').html_safe, class: 'lecture').html_safe
    end
  end

  def score_indicators(score)
    if score > 0
      full_star_tag = content_tag('div', '', class: 'score-stars full').html_safe
      half_star_tag = content_tag('div', '', class: 'score-stars half').html_safe

      rounded = score.round

      full_stars_count = rounded / 2
      half_star_count = rounded % 2

      elements = []

      full_stars_count.times do
        elements << full_star_tag.dup
      end

      half_star_count.times do
        elements << half_star_tag.dup
      end

      elements.join("").html_safe
    else
      content_tag(:p, '지금 투표해 보세요!', class: 'empty').html_safe
    end
  end

  def tagging_to_image_tag(tagging)
    tag = Tag.find(tagging.tag_id)
    style = "left: #{tagging.coord_x}px; top: #{tagging.coord_y}px"

    image_tag(asset_path(tag.image_file_name), class: 'tagged', style: style).html_safe
  end
end

app/views/lectures/_assessment.html.erb
<div class="assessment <%= assessment.best_or_worst %>">
  <% if current_user && current_user.finished_registration? %>
    <ul class="scores-list">
      <li class="score presentation" data-score="<%= assessment.presentation_score %>">
        <%= assessment.presentation_score %>
      </li>
      <li class="score workload" data-score="<%= assessment.workload_score %>">
        <%= assessment.workload_score %>
      </li>
      <li class="score grading" data-score="<%= assessment.grading_score %>">
        <%= assessment.grading_score %>
      </li>
    </ul>

    <div class="content">
      <%= assessment.content %>
    </div>
  <% else %>
    <ul class="scores-list blinded">
      <li class="score presentation">
        -1
      </li>
      <li class="score workload">
        -1
      </li>
      <li class="score grading">
        -1
      </li>
    </ul>

    <div class="content">
      &nbsp;
    </div>
  <% end %>
</div>

app/views/lectures/_assessment_form.html.erb
<div class="assessment-form-container">
  <%= form_for [registration, lecture, assessment] do |f| %>
    <div class="score-container-top">
      <div class="score-container">
        <%= f.text_field :presentation_score, :class => 'score presentation' %>
        <%= f.label :presentation_score, '수업만족' %>
      </div>
      <div class="score-container">
        <%= f.text_field :workload_score, :class => 'score workload' %>
        <%= f.label :presentation_score, '과제만족' %>
      </div>
      <div class="score-container">
        <%= f.text_field :grading_score, :class => 'score grading' %>
        <%= f.label :presentation_score, '점수만족' %>
      </div>
    </div>
    <p>
      <%= f.text_area :content %>
    </p>
    <p class="actions-container">
      <%= f.submit '작성하기', :class => 'btn-submit' %>
    </p>
  <% end %>
</div>

app/views/lectures/_expanded_lecture.html.erb
<div class="expanded-lecture <%= lecture.best_or_worst %>">
  <%= link_to lecture_container(lecture), lecture %>

  <% if current_user && current_user.finished_registration? %>
    <div class="scores-container">
      <ul class="scores-list">
        <li class="overall">
          <span class="label">
            총점:
          </span>
          <span class="score">
            <%= '%.2f' % lecture.overall_score %>
          </span>
        </li>
        <li>
          <span class="label">
            수업만족:
          </span>
          <span class="score">
            <%= '%.2f' % lecture.presentation_score %>
          </span>
        </li>
        <li>
          <span class="label">
            과제만족:
          </span>
          <span class="score">
            <%= '%.2f' % lecture.workload_score %>
          </span>
        </li>
        <li>
          <span class="label">
            점수만족:
          </span>
          <span class="score">
            <%= '%.2f' % lecture.grading_score %>
          </span>
        </li>
      </ul>
      <div class="icons-container">
        <%= score_indicators(lecture.overall_score) %>

        <div class="hit-count-container stats">
          <%= lecture.hit_count %>
        </div>

        <div class="assessment-count-container stats">
          <%= lecture.assessment_count %>
        </div>

        <div class="taggings-count-container stats">
          <%= lecture.taggings.count %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="blinded">
      <%= link_to "강의평가 #{current_user.assessments_count_to_finished}개만 더 하면 자세히 볼 수 있어요 :D", lecture_path(lecture) %>
    </div>
  <% end %>
</div>

app/views/lectures/_ranked_lecture.html.erb
<div class="ranked-lecture-index <%= best_or_worst %>">
  <div class="lecture-container">
    <%= render partial: 'expanded_lecture', locals: { lecture: lecture } %>
  </div>

  <div class="rank-container">
    <%= rank %>위
  </div>

  <div style="clear: both;"></div>
</div>

app/views/lectures/index.html.erb
<%= render partial: 'shared/search_form' %>

<ul class="lectures-list">
  <% @lectures.each do |lecture| %>
    <li>
      <div class="lecture-container">
        <div class="scores-container">
          <div class="single-score">
            <div class="score-label">수업</div>
            <div class="score-value"><%= s lecture.presentation_score %></div>
          </div>
          <div class="single-score">
            <div class="score-label">학점</div>
            <div class="score-value"><%= s lecture.grading_score %></div>
          </div>
          <div class="single-score">
            <div class="score-label">과제</div>
            <div class="score-value"><%= s lecture.workload_score %></div>
          </div>
          <div class="single-score">
            <div class="score-label">시험</div>
            <div class="score-value"><%= s lecture.difficulty_score %></div>
          </div>
          <div class="single-score">
            <div class="score-label">인생</div>
            <div class="score-value"><%= s lecture.insight_score %></div>
          </div>
        </div>
        <h3><%= link_to lecture.title, lecture %></h3>
        <div class="provider"><%= lecture.provider %></div>
      </div>

    </li>
  <% end %>

  <%= will_paginate @lectures, :previous_label => '앞으로', :next_label => '뒤로' %>
</ul>

app/views/lectures/search.html.erb
<%= content_for :stylesheets do %>
  <%= stylesheet_link_tag 'search', :media => 'all' %>
<% end %>

<div id="main-container" class="login">
  <div class="searchbox-container">
    <form method="GET">
      <input name="query" class="search-input" value="<%= @query %>" />
      <input type="submit" class="btn-submit">
    </form>
  </div>

  <% if @lectures %>
    <div class="lectures left-container">
      <% @lectures[0..2].each do |lecture| %>
        <%= render partial: 'expanded_lecture', locals: { lecture: lecture } %>
      <% end %>
    </div>

    <div class="lectures right-container">
      <% if @lectures[3..-1] %>
        <% @lectures[3..-1].each do |lecture| %>
          <%= render partial: 'expanded_lecture', locals: { lecture: lecture } %>
        <% end %>
      <% end %>
    </div>

    <div class="pagination-container">
      <%= will_paginate @lectures %>
    </div>
  <% end %>
</div>

app/views/lectures/show.html.erb
  <div class="hero-unit">
    <h1>
      <%= @lecture.title %>
      <span class="provider"><%= @lecture.provider %></span>
    </h1>
    <p class="tagline scores-container">
      <span class="score-label">수업분위기</span>
      <span class="score-value"><%= s @lecture.presentation_score %></span>

      <span class="score-label">학점만족도</span>
      <span class="score-value"><%= s @lecture.grading_score %></span>

      <span class="score-label">시험</span>
      <span class="score-value"><%= s @lecture.difficulty_score %></span>

      <span class="score-label">과제</span>
      <span class="score-value"><%= s @lecture.workload_score %></span>

      <span class="score-label">인생의 멘토</span>
      <span class="score-value"><%= s @lecture.insight_score %></span>
    </p>
    <p>
      <%= link_to '평가하기', new_lecture_assessment_path(@lecture), class: 'btn btn-warning btn-large' %>
    </p>
  </div>

  <ul class="assessments-list">
    <% @assessments.each do |assessment| %>
      <div class="assessment-container">
        <div class="timestamp-container">
          <%= assessment.created_at %>
        </div>

        <%= c assessment.content %>

        <div class="scores-container">
          <div class="single-score">
            <div class="score-label">수업</div>
            <div class="score-value"><%= s assessment.presentation_score %></div>
          </div>
          <div class="single-score">
            <div class="score-label">학점</div>
            <div class="score-value"><%= s assessment.grading_score %></div>
          </div>
          <div class="single-score">
            <div class="score-label">과제</div>
            <div class="score-value"><%= s assessment.workload_score %></div>
          </div>
          <div class="single-score">
            <div class="score-label">시험</div>
            <div class="score-value"><%= s assessment.difficulty_score %></div>
          </div>
          <div class="single-score">
            <div class="score-label">인생</div>
            <div class="score-value"><%= s assessment.insight_score %></div>
          </div>
        </div>

        <div style="clear: both;"></div>
      </div>
    <% end %>
  </ul>