config/routes.rb
EwhaNote::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'user_sessions' }

  resources :lectures do
    get :search, on: :collection
    resources :assessments
  end

  resources :assessments
  resources :registrations, only: [:new, :create]

  root :to => 'assessments#index'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < Devise::SessionsController
  layout 'welcome'

  def new
    resource = build_resource(nil, :unsafe => true)
    clean_up_passwords(resource)
    respond_with(resource, serialize_options(resource))
  end

  def create
    resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    respond_with resource, :location => after_sign_in_path_for(resource)
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row first-view-container">
    <div class="span6">
      <h1 class="main-logo">DULE</h1>
    </div>
    <div class="span6 login-form-container">
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :class => 'form-horizontal' }) do |f| %>
        <div class="control-group">
          <%= f.label :username, '아이디', class: 'control-label' %>
          <div class="controls">
           <%= f.text_field :username, placeholder: '아이디' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :password, '비밀번호', class: 'control-label' %>
          <div class="controls">
           <%= f.password_field :password, placeholder: '비밀번호' %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">로그인</button>
            <%= link_to '가입하기', new_registration_path, class: 'btn' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>