config/routes.rb
EwhaNote::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'user_sessions' }

  resources :lectures do
    get :search, on: :collection
    resources :assessments
  end

  resources :assessments
  resources :registrations, only: [:new, :create]

  root :to => 'assessments#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DULE</title>
  <%= stylesheet_link_tag 'application' %>
  <%= yield :stylesheets  %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>
  <script type="text/javascript">
    /*
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-35697801-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    */
  </script>
  <script type="text/javascript">
    $(function(){
      <% if notice || alert %>
        humane.log('<%= notice || alert %>');
      <% end %>
    });
  </script>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <%= link_to 'DULE', assessments_path, class: 'brand main-navbar-logo' %>
      <ul class="nav">
        <li class="<%= @assessments ? 'active' : '' %>"><%= link_to '최신강의평', assessments_path %></li>
        <li><%= link_to '강의검색', lectures_path %></li>
      </ul>

      <% if current_user %>
        <ul class="nav pull-right">
          <li><a href="#"><%= current_user.nickname %>님 안녕하세요?</a></li>
          <li><%= link_to '로그아웃', destroy_user_session_path %></li>
        </ul>
      <% end %>
    </div>
  </div>

  <div class="container">
    <%= yield %>

    <div class="footer">
      강의평가는 어디서? 우리둘레 안에서!
      <div class="stats">
        현재 <%= User.count %>명의 학우가 <%= Assessment.count %>개의 강의평을 공유하고 있습니다.
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DULE</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    /*
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-35697801-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    */
  </script>
  <script type="text/javascript">
    $(function(){
      <% if notice || alert %>
        humane.log('<%= notice || alert %>');
      <% end %>
    });
  </script>
</head>
<body>
  <%= yield %>
  <div class="container">
    <div class="footer">
      <div class="stats">
        현재 <%= User.count %>명의 학우가 <%= Assessment.count %>개의 강의평을 공유하고 있습니다.
      </div>
    </div>
  </div>
</body>
</html>